import{useEffect,useState}from 'react'
import{Link}from 'react-router-dom'
import{Check,X,MessageSquareWarning,Stethoscope,ShieldCheck}from 'lucide-react'
import{supabase}from '../lib/supabase'
import{useAuth}from '../context/AuthContext'
import type{Species,SightingStatus}from '../lib/types'
import{STATUS_LABELS}from '../lib/types'
const PND:SightingStatus[]=['aguardando_revisao','em_revisao','correcao_solicitada','revisao_especialista']
interface Item{id:string;status:SightingStatus;municipio:string|null;observation_date:string|null;notes:string|null;reported_name:string|null;dont_know_species:boolean;confirmed_species_id:string|null;suggested:{common_name:string}|null}
export default function Moderation(){const{session,isModeratorOrAdmin,isAdmin}=useAuth();const[items,setItems]=useState<Item[]>([]);const[species,setSpecies]=useState<Species[]>([]);const[loading,setLoading]=useState(true);const[busyId,setBusyId]=useState<string|null>(null);const[cc,setCc]=useState<Record<string,string>>({})
  async function load(){setLoading(true);const{data}=await supabase.from('sightings').select('id,status,municipio,observation_date,notes,reported_name,dont_know_species,confirmed_species_id,suggested:species!sightings_species_id_fkey(common_name)').in('status',PND).order('created_at',{ascending:true});setItems(((data as unknown as Item[])??[]));setLoading(false)}
  useEffect(()=>{if(!isModeratorOrAdmin)return;load();supabase.from('species').select('*').eq('active',true).order('common_name').then(({data})=>setSpecies((data as Species[])??[]))},[isModeratorOrAdmin])
  async function act(id:string,status:SightingStatus,action:string,message?:string){if(!session)return;setBusyId(id);await supabase.from('sightings').update({status,reviewed_by:session.user.id,review_note:message??null}).eq('id',id);await supabase.from('moderation_actions').insert({sighting_id:id,actor_id:session.user.id,action,message:message??null});if(status==='aprovado'){supabase.functions.invoke('send-sighting-notification',{body:{sighting_id:id}}).catch(()=>{})};setItems((p)=>p.filter((i)=>i.id!==id));setBusyId(null)}
  async function reqCorr(id:string){const msg=window.prompt('O que precisa ser corrigido?');if(!msg)return;await act(id,'correcao_solicitada','correcao_solicitada',msg)}
  async function confSp(id:string){const spId=cc[id];if(!spId||!session)return;setBusyId(id);await supabase.from('sightings').update({confirmed_species_id:spId,identified_by:session.user.id}).eq('id',id);await supabase.from('moderation_actions').insert({sighting_id:id,actor_id:session.user.id,action:'identificacao_confirmada'});setBusyId(null);load()}
  if(!isModeratorOrAdmin)return <p className="center-note">Esta área é restrita a moderadores.</p>
  return(<div className="page"><div style={{display:'flex',alignItems:'center',gap:'0.6rem',marginBottom:'1rem'}}><ShieldCheck size={22} color="var(--vermelho)"/><h1 style={{margin:0}}>Moderação</h1></div><p>Registros aguardando revisão.</p>{loading&&<p className="center-note">Carregando…</p>}{!loading&&items.length===0&&<p className="center-note">Nenhum registro pendente. 🎉</p>}<div style={{display:'grid',gap:'0.8rem'}}>{items.map((it)=>(<div className="card" key={it.id}><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:'0.5rem'}}><strong style={{fontSize:'0.95rem'}}>{it.dont_know_species?(it.reported_name||'Não identificada'):it.suggested?.common_name}</strong><span className="status-tag" style={{background:'var(--amarelo-bg)',color:'var(--amarelo-alerta)'}}>{STATUS_LABELS[it.status]}</span></div><div style={{fontSize:'0.78rem',color:'var(--cinza-fraco)',marginBottom:'0.5rem'}}>{it.municipio??'—'} · {it.observation_date?new Date(it.observation_date).toLocaleDateString('pt-BR'):''}</div>{it.notes&&<p style={{fontSize:'0.85rem',margin:'0 0 0.5rem'}}>{it.notes}</p>}<Link to={`/registro/${it.id}`} style={{fontSize:'0.78rem',fontWeight:700,display:'block',marginBottom:'0.7rem'}}>Ver registro →</Link>{isAdmin&&(<div style={{display:'flex',gap:'0.4rem',marginBottom:'0.7rem'}}><select className="input" style={{flex:1,fontSize:'0.82rem',padding:'0.5rem 0.6rem'}} value={cc[it.id]??''} onChange={(e)=>setCc((c)=>({...c,[it.id]:e.target.value}))}><option value="">Confirmar espécie…</option>{species.map((s)=><option key={s.id} value={s.id}>{s.common_name} ({s.venomous?'peçonhenta':'não peçonhenta'})</option>)}</select><button className="btn btn-vermelho btn-sm btn-auto" style={{borderRadius:'8px'}} disabled={!cc[it.id]||busyId===it.id} onClick={()=>confSp(it.id)}>OK</button></div>)}<div style={{display:'flex',gap:'0.4rem',flexWrap:'wrap'}}><button className="btn btn-vermelho btn-sm btn-auto" style={{borderRadius:'8px'}} disabled={busyId===it.id} onClick={()=>act(it.id,'aprovado','aprovado')}><Check size={14}/> Aprovar</button><button className="btn btn-outline btn-sm btn-auto" style={{borderRadius:'8px'}} disabled={busyId===it.id} onClick={()=>reqCorr(it.id)}><MessageSquareWarning size={14}/> Correção</button><button className="btn btn-outline btn-sm btn-auto" style={{borderRadius:'8px'}} disabled={busyId===it.id} onClick={()=>act(it.id,'revisao_especialista','revisao_especialista')}><Stethoscope size={14}/> Especialista</button><button className="btn btn-danger btn-sm btn-auto" style={{borderRadius:'8px'}} disabled={busyId===it.id} onClick={()=>act(it.id,'rejeitado','rejeitado')}><X size={14}/> Rejeitar</button></div></div>))}</div></div>)
}
